# https://www.mkdocs.org/user-guide/configuration/
# https://www.mkdocs.org/user-guide/writing-your-docs/
# https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown
# https://mkdocs.readthedocs.io/en/0.15.2/user-guide/writing-your-docs/
# https://mkdocs.readthedocs.io/en/0.15.2/user-guide/styling-your-docs/
# https://example-mkdocs-basic.readthedocs.io/en/latest/
# https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml
# https://squidfunk.github.io/mkdocs-material/creating-your-site/
# mkdocs.yml

site_name: PSReddit
site_url: https://LukeEvansTech.github.io/PSReddit/
repo_url: https://github.com/LukeEvansTech/PSReddit/
repo_name: LukeEvansTech/PSReddit
# edit_uri: edit/main/docs/
# edit_uri_template:
site_description: PSReddit is a cross-platform PowerShell 7+ module for interacting  with the Reddit API # meta tag to the generated HTML header
site_author: Luke Evans # meta tag to the generated HTML header
# copyright:
# remote_branch:
# remote_name:
# docs_dir: docs
# site_dir:
# extra_css:
# extra_javascript:
markdown_extensions:
  # Python Markdown
  - admonition
  - toc:
      permalink: true
  # Code highlighting - requires Pygments
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# extra_templates:
# extra:
theme:
  name: material
  # language: en
  # custom_dir: overrides
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.path
  # favicon:
  icon:
    repo: fontawesome/brands/github # Or fontawesome/brands/git-alt
  # font:
  #   text: Work Sans
  # logo:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue # Set light mode primary color
      accent: light blue        # Optional accent color
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue     # Optional dark mode primary color (can be customized)
      accent: light blue        # Optional accent color
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Change Log: CHANGELOG.md
  - Development: DEVELOPMENT.md
  # - Functions:
  #   - Function1: functions/function1.md
